apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- prometheus-configmap.yaml
- prometheus-deployment.yaml
- prometheus-service.yaml
- grafana-deployment.yaml
- grafana-service.yaml
- grafana-secrets.yaml

namespace: monitoring

commonLabels:
  app.kubernetes.io/part-of: monitoring