apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- hpa.yaml
- network-policy.yaml
- pdb.yaml

namePrefix: prod-

patchesStrategicMerge:
- patches/deployment-patch.yaml
- patches/configmap-patch.yaml

replicas:
- name: sequential-questioning
  count: 3 