apiVersion: apps/v1
kind: Deployment
metadata:
  name: sequential-questioning
spec:
  template:
    spec:
      containers:
      - name: sequential-questioning
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        env:
        - name: DEBUG
          value: "false"
        - name: METRICS_ENABLED
          value: "true" 