apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgres-deployment.yaml
- postgres-service.yaml
- postgres-pvc.yaml
- postgres-secret.yaml

namespace: sequential-questioning

commonLabels:
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: mcp-server 