apiVersion: apps/v1
kind: Deployment
metadata:
  name: sequential-questioning
spec:
  template:
    spec:
      containers:
      - name: sequential-questioning
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: DEBUG
          value: "true"
        - name: LOG_LEVEL
          value: "DEBUG" 