apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ingress.yaml
- ../database

namespace: sequential-questioning

commonLabels:
  app.kubernetes.io/name: mcp-server
  app.kubernetes.io/part-of: sequential-questioning 