apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: dev-

patchesStrategicMerge:
- patches/deployment-patch.yaml
- patches/configmap-patch.yaml

replicas:
- name: sequential-questioning
  count: 1 